apiVersion: v1
data:
  dbkind: postgresql
  dbpass: mijngeheimwachtwoord
  dburl: jdbc:postgresql://postgres:5432/postgres
  dbuser: postgres
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"dbkind":"postgresql","dbpass":"mijngeheimwachtwoord","dburl":"jdbc:postgresql://postgres:5432/postgres","dbuser":"postgres"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"auditservice","namespace":"default"}}
  creationTimestamp: "2026-06-10T14:27:47Z"
  name: auditservice
  namespace: default
  resourceVersion: "26161"
  uid: 0ac1e925-b15e-415f-ab11-84b007a82a64
