
@host = http://localhost:8080
# @host = http://localhost:9001

### Create Task
POST {{host}}/tasks
Content-Type: application/json

{
  "taskName": "Wasje draaien",
  "dueDate": "2026-06-12"
}

### Complete Task
PUT {{host}}/tasks/complete/cf05ae55-3ad9-4f53-88d3-ea7ac4f788f3

### Find Tasks
GET {{host}}/tasks

### Find completed Tasks
GET {{host}}/tasks/complete

### Delete completed Tasks
DELETE {{host}}/tasks